### PR TITLE
Add blockResubmit to documentation

### PR DESCRIPTION
**Pull request by AltayAkkus**
See https://github.com/shopware/platform/pull/2899

### CODE REVIEW

**Comment by mstegmeyer** [comment]
As discussed in https://github.com/shopware/platform/pull/2899, please change the default value

**Comment by mstegmeyer** [comment]
Please add a notice, that this feature is only available with the Shopware version, that this will be released with (Most likely Shopware 6.5.0.0, if the merge goes through in the next few weeks)

**Comment by elkmod** [comment]
Changed target to `docs:master` because it reflects 6.5 state as of today.

**Comment by elkmod** [comment]
Still blocked as @buzyka is resolving merge conflicts.

**Review by mstegmeyer — APPROVED** [review]

**Pull request merged**
