### PR TITLE
Update add-custom-controller.md

### PR DESCRIPTION
**Pull request by daslicht**
added missing ```method="setTwig"``` call

### CODE REVIEW

**Comment by Isengo1989** [comment]
For future reference

## Storefront Controller need to have Twig injected in future versions

The `twig` service will be private with upcoming Symfony 6.0. To resolve this deprecation, a new method `setTwig` was added to the `StorefrontController`.
All controllers which extends from `StorefrontController` need to call this method in the dependency injection definition file (services.xml) to set the Twig instance.
The controllers will work like before until the Symfony 6.0 update will be done, but they will create a deprecation message on each usage.
Below is an example how to add a method call for the service using the XML definition.

### Before

```xml
<service id="Shopware\Storefront\Controller\AccountPaymentController">
    <call method="setContainer">
        <argument type="service" id="service_container"/>
    </call>
</service>
```

### After

```xml
<service id="Shopware\Storefront\Controller\AccountPaymentController">
    <call method="setContainer">
        <argument type="service" id="service_container"/>
    </call>
    <call method="setTwig">
        <argument type="service" id="twig"/>
    </call>
</service>
```

**Comment by Isengo1989** [comment]
@daslicht could you add it in [# Add Dynamic Content via AJAX Calls](https://developer.shopware.com/docs/guides/plugins/plugins/storefront/add-dynamic-content-via-ajax-calls.html#add-dynamic-content-via-ajax-calls) as well, so we got it covered for the future :slightly_smiling_face:

**Review by Isengo1989 — CHANGES_REQUESTED** [review]
Please add info to other [example](https://developer.shopware.com/docs/guides/plugins/plugins/storefront/add-dynamic-content-via-ajax-calls.html#add-dynamic-content-via-ajax-calls)

**Comment by daslicht** [comment]
> Please add info to other [example](https://developer.shopware.com/docs/guides/plugins/plugins/storefront/add-dynamic-content-via-ajax-calls.html#add-dynamic-content-via-ajax-calls)

created pull request here https://github.com/shopware/docs/pull/1178

**Comment by Isengo1989** [comment]
@daslicht ok, that work's as well :slightly_smiling_face: 

Thanks for the PR :tada:

**Pull request merged**
