### PR TITLE
Shell script code got lost in a previous merge

### PR DESCRIPTION
**Pull request by jhit**

### CODE REVIEW

**Review by shyim — APPROVED** [review]

**Comment by jhit** [comment]
The linter complains about Code outside my MR (line 166). I will not fix that.

**Comment by Christian-Rades** [comment]
@jhit Line 166 is fixed now, you can rebase then we can merge it

**Comment by jhit** [comment]
I made a rebase but the result is pretty messed up. I do not understand why all the commits are duplicated now.
I did clone this repo -> add upstream -> pull upstream -> checkout fix-branch -> rebase master.
After that I was not able to push. and needed to pull remote changes for the fix-branch. Some fast forward messup.
I can recreate the fix in a clean fork if you like.

**Comment by Christian-Rades** [comment]
@jhit You can use a clean fork or try and git reset --hard your commit. Anyways, fixing it is much appreciated 💙

**Comment by jhit** [comment]
@Christian-Rades ok, I got it sorted out. Should be ready to merge.

**Review by Christian-Rades — APPROVED** [review]

**Comment by Christian-Rades** [comment]
Thank you!

**Pull request merged**
