### PR TITLE
remove twig cache changing path

### PR DESCRIPTION
**Pull request by shyim**
This will be deprecated in Symfony 7.1, and it makes no sense to move it

### CODE REVIEW

**Comment by Isengo1989** [comment]
@shyim is it already removed and we are running 7.1 (since 7.1 is only dev so far) ?

**Comment by shyim** [comment]
we are running 7.0 and it will be deprecated in 7.1

**Comment by Isengo1989** [comment]
@shyim I don't think this is used very commonly, but we will leave the PR open until the functionality is fully removed. I will add the label blocked for now.

**Review by Isengo1989 — APPROVED** [review]
Thank you for the PR :tada: 

Merged as soon as the version is released

**Pull request merged**
