### PR TITLE
B2B-870 - B2B-Suite administration docs

### PR DESCRIPTION
**Pull request by dfrancos-hub**
This doc provides only an overview of the administration modules. When the Quick Start and the Offer guides are created, links to those pages will be also added here.

### CODE REVIEW

**Comment by bschulzebaek** [comment]
@dfrancos-hub maybe we should consider linking the administration page to the end user docs, instead of showing those two screenshots. The user docs can be found [here](https://docs.shopware.com/de/shopware-6-de/enterprise-erweiterungen/b2b-suite-administration).

**Comment by dfrancos-hub** [comment]
thanks @bschulzebaek ,you are right I think thats better. Although the Offer management module is only described in the german version of the user documentation. What do you think? should we keep the second screenshot or removing it anyways?

**Comment by bschulzebaek** [comment]
Maybe you could reach out to the responsible docs team then, so they can provide an english version as well 👍 
I would like to prevent having the same information in different places, where both would require some maintenance.

**Comment by dfrancos-hub** [comment]
Agree @bschulzebaek 👍, ok ill reach them. Then, any further changes here?

**Comment by bschulzebaek** [comment]
I would just remove the two paragraphs regarding "Extended Customer Details" and "Offers Module
". We will probably need to document some specific components or concepts of the b2b administration code (yet never really was an issue in support tickets, iirc), but right now, we want to focus on migrating the old documentation, not documenting everything, thats possibly missing right now.

**Comment by dfrancos-hub** [comment]
Hi @bschulzebaek I totally agree, actually those paragraph are there only because it was suggested in the ticket :)

**Comment by dfrancos-hub** [comment]
@bschulzebaek done ;)

**Review by bschulzebaek — APPROVED** [review]

**Pull request merged**
