### PR TITLE
typo: Update add-payment-plugin.md

### PR DESCRIPTION
**Pull request by panakour**
fixes typo on calling the transactionStateHandler obj

### CODE REVIEW

**Comment by Isengo1989** [comment]
@panakour thx for the PR and find :slightly_smiling_face: 

Can you please fix the others as well, I found 3 others in the doc

**Comment by panakour** [comment]
@Isengo1989 thanks for let me know for the others as well. I'v updated all

**Comment by Isengo1989** [comment]
> @Isengo1989 thanks for let me know for the others as well. I'v updated all

You missed another one, 3 mentioned, 2 fixed :smile: 

`Line 440`

**Comment by panakour** [comment]
done!

**Review by Isengo1989 — APPROVED** [review]
Thx for you PR @panakour :tada:

**Pull request merged**
