### PR TITLE
Add a guide for creating own twig functions

### PR DESCRIPTION
**Pull request by Tschucki**
During the theme development for a shop, I often got to the point where I wished there was a Twig Function for it.

For example:
Check if a product is within a given category.
Find all available variants for a product
Flatten category tree
Find sibling categories
Find out how many products are in a category
etc.

Unfortunately I couldn't find anything about this in the documentation.

That's why I think the guide should be included in the documentation.

The attached commit contains that guide. (kinda)

### CODE REVIEW

**Comment by ssltg** [comment]
Hi @Tschucki ,
thank you for your contribution. Your documentation is well written 👍 
Two things:
1. The documentation should also include an example how the new function is used in a template (it is obvious, but better have it, than someone has to ask)
2. More serious: The chosen example is not the best to provide. Of course one can do such a twig function, but it is not recommended to add DAL Calls inside twig functions because of performance and cache reliability. Can you change the example to something that works on the provided Page data in a template?

If you currently use twig functions to get more data you are missing, you should follow this guide instead: https://developer.shopware.com/docs/guides/plugins/plugins/storefront/add-data-to-storefront-page

regards,
Stefan

**Review by ssltg — COMMENTED** [review]
...

**Review by ssltg — CHANGES_REQUESTED** [review]
See comment https://github.com/shopware/docs/pull/462#issuecomment-1005718519

**Comment by elkmod** [comment]
@Tschucki - could you please provide a different example, which does adhere to the "guidelines" @ssltg mentioned above? E.g. a "hash" method, which returns hashed string of a certain input string?

**Comment by elkmod** [comment]
We're closing this PR for inactivity. It remained open, because it doesn't adhere to our guidelines yet. Feel free to reopen, once those issues are resolved.

**Pull request closed without merging**
