### PR TITLE
WIP: Markdown Content Migration

### PR DESCRIPTION
**Pull request by elkmod**
We are preparing to migrate our documentation frontend to [our new documentation template](https://github.com/shopware/developer-documentation-vitepress) which will allow us to improve some aspects:

* Search 🔎
* Navigation 🗺
* Interactive examples 🪄
* Unified structure with other documentations (Extension API, PWA, API References) ☂️
* Dark Mode ✨

A lot of content contains GitBook-specific syntax and therefore needs to be refactored / migrated in order to work with the new frontend. This pull request will be the main stream for all discussions and contributions toward the migration.

## Setup

To contribute, set up the developer documentation frontend locally and "mount" documentation into the `demo/docs` directory:

```bash
$ git clone git@github.com:shopware/developer-documentation-vitepress.git docs-frontend
$ cd docs-frontend/demo
$ git clone git@github.com:shopware/docs.git
$ cd docs && git checkout refactor-vitepress-format
$ cd ../../
$ npm install && npm run dev
```

## What needs to be changed

* File names
* Links
* Page References
* Page Embeds
* Hints
* Code blocks

### File names

Rename all `README.md` to `index.md`

### Links

All links and references should be relative (if applicable).

Links should not include a file suffix: 

```markdown
[Sales Channel](../../concepts/sales-channel.md) // WRONG!!!

[Sales Channel](../../concepts/sales-channel) // CORRECT
```

### Page references

Use the new `PageRef` component

```markdown
{% page-ref page="guides/plugins/" %}
```

becomes

```markdown
<PageRef
	page="guides/plugins/"
	title="Create a custom API endpoint"
	sub="Shows you how to extend the API with a custom defined endpoint" />
```

Attention - a `title` has to be set - `sub` is optional
use `<Page Ref ... video />` in order to set a video icon.

### Page Embeds

Use the new `PageRef` component with `target="_blank"`

```markdown
{% embed url="https://github.com/shopware/recipes/blob/main/shopware/fastly-meta/6.4/config/fastly/deliver.vcl" caption="vcl_deliver" %}
```

becomes

```markdown
	<PageRef
	page="https://github.com/shopware/recipes/blob/main/shopware/fastly-meta/6.4/config/fastly/deliver.vcl"
	title="vcl_deliver"
	target="_blank" />
```

### Hints

```markdown
{% hint style="info" %}
Categories can be globally hidden from store navigations based on a hide in navigation flag.
{% endhint %}
```

becomes

```markdown
::: info
Categories can be globally hidden from store navigations based on a hide in navigation flag.
:::
```

Other options are `tip`, `warning` or `danger` . Also `details` is possible to have a collapsible container. Another title can be set as well

```markdown
::: info Important!
This is an important message
:::
```

### Codeblocks

The `markup` syntax is not supported anymore, use `xml` or something applicable instead.

```markdown
```markup
```

becomes

```markdown
```xml
or
```html
```

and 

````markdown
{% code title="<plugin root>src/Resources/config/service.xml" %}

```markup
<service id="Swag\ExamplePlugin\Service\DalExampleService">
    <argument type="service" id="product.repository"/>
</service>
```

{% endcode %}
````

becomes

````markdown

```xml
// <plugin root>src/Resources/config/service.xml
<service id="Swag\ExamplePlugin\Service\DalExampleService">
    <argument type="service" id="product.repository"/>
</service>
```

````

### CODE REVIEW

**Comment by JoshuaBehrens** [comment]
Will old URLs redirect correctly for external pages linking the documentation?

**Comment by elkmod** [comment]
@JoshuaBehrens yes - since the directory structure will be the same in `/docs`, all old links will still work.

**Comment by JoshuaBehrens** [comment]
@elkmod nice

**Comment by bojanrajh** [comment]
Closing in favour of https://github.com/shopware/docs/pull/850 .

**Pull request closed without merging**
