### PR TITLE
added docs for count sorting

### PR DESCRIPTION
**Pull request by dneustadt**
https://gitlab.shopware.com/shopware/6/product/platform/-/merge_requests/7920

### CODE REVIEW

**Review by JoshuaBehrens — APPROVED** [review]

**Comment by elkmod** [comment]
@dneustadt - could you enhance the reference with an example that shows how the count sorting works? E.g. by showing the result together with the results of a bucket aggregation on the field whose association is sorted by.

As of now, it's probably not clear to people what this does exactly.

**Review by elkmod — CHANGES_REQUESTED** [review]
See comment

**Review by elkmod — APPROVED** [review]
Everything clear, thank you!

**Comment by elkmod** [comment]
Starting from which version is this feature available? @dneustadt

**Comment by dneustadt** [comment]
> Starting from which version is this feature available? @dneustadt

It's scheduled for the next minor release.

**Review by elkmod — APPROVED** [review]

**Pull request merged**
